apiVersion: v1
kind: Service
metadata:
  labels:
    run: rabbitmq
  name: rabbitmq
spec:
  ports:
  - name: amqp
    port: 5672
    protocol: TCP
    targetPort: 5672
  - name: management
    port: 15672
    protocol: TCP
    targetPort: 15672
  selector:
    run: rabbitmq
status:
  loadBalancer: {}
